### ISSUE TITLE
stack: dockerize all apps that we use in separate repos

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara-infra#9]
we should create a Dockerfile (and push it to gh registry) for every app that we use that don't have a amd64/arm64 image available

**Comment by d-roak** [comment]
mostly fixed with #16 (missing arm64 for apibara cc @fracek)

**Comment by fracek** [comment]
We started building (and tagging) arm images this week https://quay.io/repository/apibara/starknet?tab=tags I recommend using the `latest` or `1` tag.

**Comment by d-roak** [comment]
#18 fixes this
